In [1]:
import numpy as np
import numpy.random as npr
import matplotlib.pyplot as plt
import rpy2.robjects as robj
import pyreadr
from easydict import EasyDict as edict
from tqdm import tqdm_notebook as tqdm
import sys
import time as Time
import pickle
from scipy.io import loadmat
from scipy.signal import decimate, detrend
import seaborn as sns
%matplotlib inline

In [2]:
sys.path.append("/home/huaqingj/MyResearch/dynamicR2py")
from utils import *

In [3]:
MEG = loadmat("./data/subj2.mat")["DK_timecourse"]

In [4]:
q = 10

In [5]:
MEGlist = []
for i in range(MEG.shape[0]):
    MEGlist.append(decimate_R(MEG[i, :], q))

R[write to console]: 
Attaching package: ‘signal’


R[write to console]: The following objects are masked from ‘package:stats’:

    filter, poly




In [6]:
MEGarr = np.array(MEGlist)

In [8]:
MEGarr[:3, :3]

array([[ -1011.71153893,  -2069.24763873,  -1891.61620176],
       [ -5465.3075002 , -10931.59863181,  -9831.38733932],
       [   483.90798049,   1056.44483281,    971.50477391]])

In [15]:

d, n = MEG.shape
time = np.linspace(0, 2, n)

In [19]:
dXmat, Xmat = GetBsplienEst(MEG, time, 1e-4)

In [21]:
Xmat[:3, :3]

array([[-1868.11691628, -1872.43086233, -1876.74474389],
       [-9294.84883011, -9411.67463566, -9528.49844922],
       [  980.22313476,   990.28081154,  1000.3383923 ]])

In [22]:
Amat = GetAmat(dXmat, Xmat, time, 20, fct=0.5)

In [23]:
Amat[:3, :3]

array([[   8.79347264,   32.81815481,  -16.12558216],
       [  74.53534255,  190.76560784, -101.57178903],
       [  -6.34976214,   -7.93651025,    6.84432231]])

In [27]:
Res = GetNewEst(dXmat, Xmat, Amat, r=8, is_full=True)
ndXmat, nXmat = Res.ndXmat, Res.nXmat

In [31]:
ndXmat[:, :2]

array([[ 1.51289946e+05,  1.51294191e+05],
       [ 1.87838545e+05,  1.87836760e+05],
       [-3.90607548e+05, -3.90608227e+05],
       [-1.07847556e+05, -1.07823116e+05],
       [-3.60409157e+04, -3.60387509e+04],
       [-1.05591356e+05, -1.05589349e+05],
       [-1.26721274e+04, -1.26704279e+04],
       [ 4.27743820e-10,  4.27729470e-10],
       [ 7.79373510e+04,  7.79159854e+04],
       [-2.02846785e-09, -2.02843273e-09]])

In [46]:
res = EGenDy(ndXmat, nXmat, kappa=1.2, Lmin=18, MaxM=15, diag=True)

Main Loop: 100%|██████████| 180/180 [00:02<00:00, 61.57it/s]


In [47]:
chg3 = res.chgMat[2, :]
chg3 = chg3[chg3!=np.inf]
tStep = np.diff(time)[0]

In [48]:
EstXmat = ReconXmat(chg3, ndXmat, nXmat, Res.kpidxs, Res.eigVecs, TrueXmat, tStep)

In [49]:
EstXmat[:3, :3]

array([[ 0.00092553,  0.00094414,  0.00097186],
       [-0.00296006, -0.00301639, -0.00306042],
       [ 0.00107859,  0.00109312,  0.00113217]])

In [4]:
x = np.arange(10)

In [8]:
np.where(x>4)[0]-1

array([4, 5, 6, 7, 8])